# build.yml
name: Try to build
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install yarn
      - run: yarn install
      - run: yarn build
